// <auto-generated />
using System;
using ForumApp.Data.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Data.Core.Migrations
{
    [DbContext(typeof(ForumAppContext))]
    [Migration("20240926091525_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a145efb-b308-42fc-bf31-1e63329a3d22"),
                            Content = "Content for post 1.",
                            IsDeleted = false,
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = new Guid("d591275e-10a0-4ac2-aa70-8ad791ab56ea"),
                            Content = "Content for post 2.",
                            IsDeleted = false,
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = new Guid("ebd191a5-a0bb-41a5-b92c-8b7dcc91dc7c"),
                            Content = "Content for post 3.",
                            IsDeleted = false,
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = new Guid("e819792c-9e28-487f-b164-03d30e7eed9c"),
                            Content = "Content for post 4.",
                            IsDeleted = false,
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = new Guid("a13cd027-6f8a-48dd-a1c1-b3cae4b21193"),
                            Content = "Content for post 5.",
                            IsDeleted = false,
                            Title = "Post 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
